#!/usr/bin/python3
try:from pathlib import Path as P;R=P.resolve;E=P.exists; F = R(P(__file__));\
    L = lambda p: p / 'cfg.py'; from handyPyUtil import inclPath
except: O=open(R(next(filter(E,map(L,F.parents))))); exec(O.read()); O.close()

import re

from handyPyUtil.tests import TestKit
from handyPyUtil.loggers import StdLogger

with TestKit() as tk:
    tmpDir = tk.tmpDir

    name = "mylogger"
    l = StdLogger(name, tmpDir)

    MSG1 = "This is message 1"
    l.info(MSG1)

    f = tmpDir / (name + '.log')
    assert f.exists()

    s = f.read_text().split("\n")[0]
    assert re.search(MSG1, s)
