#!/usr/bin/python3
from pathlib import Path as P; E=P.exists;R=P.resolve; l=R(P(__file__)).parents
with open(R(next(filter(E,(p/'cfg.py' for p in l))))) as _:exec(_.read())

import re

from handyPyUtil.tests import TestKit
from handyPyUtil.loggers import StdLogger

with TestKit() as tk:
    tmpDir = tk.tmpDir

    name = "mylogger"
    l = StdLogger(name, tmpDir)

    MSG1 = "This is message 1"
    l.info(MSG1)

    f = tmpDir / (name + '.log')
    assert f.exists()

    s = f.read_text().split("\n")[0]
    assert re.search(MSG1, s)
