#!/usr/bin/python3
import re
from pathlib import Path
cfgDir = Path(__file__).resolve().parent.parent.parent
cfgFile = cfgDir/ 'cfg.py'
with open(str(cfgFile)) as O: exec(O.read())

from pathlib import Path

from handyPyUtil.tests import TestKit
from handyPyUtil.subproc import Pipe

bpltFile = cfgDir / 'boilerplate_for_scripts'
bplt = bpltFile.read_text()

with TestKit() as tk:
    tmpDir = tk.tmpDir

    tk.createTree({
        'mypkg': {
            '__init__.py': "",
            'cfg.py': cfgFile,
            'client': {
                '__init__.py': "",
                'funcs.py': "def f(): pass",
            },
            'server': {
                '__init__.py': "",
            },
            'scripts': {
                '__init__.py': "",
                "myscript.py": f"""
{bplt}

from ..client.funcs import f
f()
"""[1:-1],
                "run_myscript.py": f""",
{bplt}

import mypkg.scripts.myscript
"""[1:-1],
            },
        },
    })

    for scr in map(lambda s: tmpDir / f'mypkg/scripts/{s}.py', (
        'run_myscript',
        'myscript',
    )):
        p = Pipe(['python3', str(scr)])
        errMsg = f"the script {scr} failed with status={p.status}:\n{p.stdout}\n{p.stderr}"
        assert p.status == 0, errMsg
